New Pipeline

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -49,12 +49,12 @@ jobs:
       - name: Run container
         run: docker run -d --name little_devoop devoops:latest -p 8080:8080 --restart always
 
-      - name: Stop container
-        run: docker stop little_devoop
+    #  - name: Stop container
+    #    run: docker stop little_devoop
 
-      - name: Cleanup container
-        run: |
-          docker stop little_devoop || true
+     # - name: Cleanup container
+      #  run: |
+       #   docker stop little_devoop || true
         # docker rm little_devoop || true
 
 
